### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by pemsft** [dawlysd/azure-dns-private-resolver-microhack#3]
Thank you for a great Microhack!

A small typo in Challenge 3, Task 3.
For better test results I would recommend replacing "privatelink.postgresql.database.azure.com" with "privatelink.postgres.database.azure.com" in sentence:
"Sending the DNS queries for contoso.azure and privatelink.postgresql.database.azure.com to the hub private DNS resolver 10.221.2.4".

**Comment by dawlysd** [comment]
Thank you very much @pemsft, it is fixed :)
